spring:
  datasource:
    generate-unique-name: false
    name: tacocloud
    #datasource:
      #url:
      # jdbc:postgresql://localhost:5432/<bd_name>
      #username: <tacouser>
      #password: <tacopassword>
      #driver-class-name: com.mysql.jdbc.Driver